#Theme and Set Up
lsi: false
safe: true
source: DIR
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: thiagorossener/jekflix-template
