name: newurbanist
title: a personal site
description: somewhere for me to place the thoughts that keep me up

tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
email: jenfox54@gmail.com

show_hero: true

menu:
  - title: elevator intro
    url: /elevator
  - title: several hours in elevator intro
    url: /XLevator
  - title: overthoughts
    url: /overthoughts
  - title: ongoings
    url: /ongoings
